name: CI / Pipeline de Pruebas

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas unitarias (Jest)
      run: npm test