name: Pipeline CI/CD - Banda de Guerra UNEFA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v3

      - name: Configurar entorno Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Pruebas Unitarias (Suite de Pruebas)
        run: npm test

      - name: Validar Construcción del Contenedor Docker
        run: docker build -t banda-de-guerra-app .